export const SKILLS = [
    "UI Design",
    "UX Design",
    "Frontend",
    "Backend",
    "Full Stack",
    "React",
    "Next.js",
    "Node.js",
    "TypeScript",
    "Flutter",
    "React Native",
    "AI",
    "Gemini",
    "OpenAI",
    "DevOps",
    "QA",
    "Motion Design",
    "Brand Design",
  ] as const;